### ISSUE TITLE
No time

### ISSUE THREAD

**Issue by xvw** [RMEx/LD33#1]
J'avais une réunion aujourd'hui, ce qui fait que je n'ai pas eu du tout le temps d'avancer dans le jeu :/ et ce soir ma copine vient. DONC j'essayerai de travailler une fois qu'elle dormira... c'est à dire... tard :/ . 
Un patch NUKI-version existe sur le repo. Toutes les maps sont construites. 
-    [ ]   Intégrer intelligemment le système de combat de Bastien en copiant les évènements communs dans la base de données (ceux actuels ne sont plus à jours) 
-    [ ]   Faire de la musique (village, donjon, combat, title) et des bruitages (coffres, porte, save/load)
-    [ ]   Faire un écran titre 
-    [ ]   Refaire la terre qui est dégueue et les soucoupes. 

FORCE ET HONNEUR !

**Comment by BastienDuplessier** [comment]
Yo gros PD.

Je m'occupe de la première étape. Tout le jeu est bon sinon ? Le fil
principal ? Les élément annexes ? La fin ? Je m'occuperais de faire une
béta test très poussée pour voir s'il y a des bugs ou des défauts à fixer.
Pour le reste j'ajouterais qu'il y a une image de game over à réaliser
aussi. (si c'est pas déjà fait).

Je rentre chez moi surement vers 19h30. Je m'y mets dès lors.

NIKSAMER LA PUTE

Le 24 août 2015 15:53, Xavier Van de Woestyne notifications@github.com a
écrit :
